// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBZGwS4CL7CA2_XuPOWCa_P2KGdIzN6PcE',
    appId: '1:85822490576:web:fd447bc6ebd1e7328c9bd5',
    messagingSenderId: '85822490576',
    projectId: 'studentattendanceapp-bc895',
    authDomain: 'studentattendanceapp-bc895.firebaseapp.com',
    storageBucket: 'studentattendanceapp-bc895.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBrB5-qkQpzX4-qK_sNP52FWKgiD_OGPME',
    appId: '1:85822490576:android:3b52439235da0d028c9bd5',
    messagingSenderId: '85822490576',
    projectId: 'studentattendanceapp-bc895',
    storageBucket: 'studentattendanceapp-bc895.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDlamHzTAO5MzALpab9Qiw24n6_crt1O6Y',
    appId: '1:85822490576:ios:71dbe81d87223ce58c9bd5',
    messagingSenderId: '85822490576',
    projectId: 'studentattendanceapp-bc895',
    storageBucket: 'studentattendanceapp-bc895.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDlamHzTAO5MzALpab9Qiw24n6_crt1O6Y',
    appId: '1:85822490576:ios:71dbe81d87223ce58c9bd5',
    messagingSenderId: '85822490576',
    projectId: 'studentattendanceapp-bc895',
    storageBucket: 'studentattendanceapp-bc895.firebasestorage.app',
    iosBundleId: 'com.example.attendance',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBZGwS4CL7CA2_XuPOWCa_P2KGdIzN6PcE',
    appId: '1:85822490576:web:d35b74e0a5e3cdc18c9bd5',
    messagingSenderId: '85822490576',
    projectId: 'studentattendanceapp-bc895',
    authDomain: 'studentattendanceapp-bc895.firebaseapp.com',
    storageBucket: 'studentattendanceapp-bc895.firebasestorage.app',
  );
}
